version: '3.8'
services:
  react:
    build: ./FrontEnd
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd:/app
    depends_on:
      - spring-boot
    environment:
      - VITE_API_URL=http://spring-boot:8080
  spring-boot:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/EducationalInstituteManagement
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Root@123
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=EducationalInstituteManagement
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/schema_with_data.sql:/docker-entrypoint-initdb.d/schema_with_data.sql
volumes:
  mysql-data: